#!/usr/bin/env python3
"""Scaffold the app-quality-polish contract package into a project.

Usage:
    python3 scaffold_configs.py <target-dir> [--platforms ios,android,web,h5,miniprogram]
                                             [--force] [--flat]

Writes into <target-dir>/quality/ (or <target-dir> with --flat):
  contract.yml              the normative clause list
  platforms.yml             declared targets, units, capability status, thresholds
  platforms/<id>.yml        the platform profile for each target
  <13 config files>         the config graph the clauses are checked against
  evidence/_TEMPLATE.yml    evidence record format
  evidence/<CLAUSE>.yml     one pending stub per evidence clause (per platform for
                            clauses declared with file_pattern)

Idempotent: existing files are skipped unless --force is passed.
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "assets" / "templates"

CONFIG_FILES = [
    "contract.yml",
    "design-token.json",
    "motion.json",
    "component-state.yml",
    "page-state.yml",
    "copy.yml",
    "perf-budget.yml",
    "a11y.yml",
    "release-gate.yml",
    "entities.yml",
    "states.yml",
    "relations.yml",
    "scenarios.yml",
    "flows.yml",
]

ALL_PLATFORMS = [
    "ios", "android", "harmonyos", "web", "h5", "miniprogram", "desktop",
    "flutter", "react-native",
]

# Preferred output order: OS surfaces first, then the runtimes that host them.
PLATFORM_ORDER = ["ios", "android", "harmonyos", "web", "h5", "miniprogram", "desktop"]
RUNTIME_ORDER = ["flutter", "react-native"]


def profile_kind(pid: str) -> str:
    """`platform` for OS surfaces, `runtime` for host frameworks."""
    import yaml

    path = TEMPLATE_DIR / "platforms" / f"{pid}.yml"
    if not path.is_file():
        return "platform"
    return (yaml.safe_load(path.read_text(encoding="utf-8")) or {}).get("kind", "platform")

STUB = """\
# Evidence stub for clause {cid}{platform_note} — generated by scaffold_configs.py
# Requirement: {requirement}
{assert_comment}clause: {cid}
platform: {platform_value}
status: pending
verified_by: ""
verified_at: ""
artifact: ""
measured:
{measured}
notes: ""
"""


def load_contract():
    import yaml

    path = TEMPLATE_DIR / "contract.yml"
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def build_platforms_yml(selected: list[str]):
    """Generate platforms.yml from the selected profiles.

    Two axes share one file: `targets` (OS surfaces) and `runtimes` (Flutter,
    React Native). A runtime is not a platform, so it gets its own list and the
    verifier checks that its hosts intersect the declared targets.
    """
    import yaml

    ordered = [p for p in PLATFORM_ORDER if p in selected] + [r for r in RUNTIME_ORDER if r in selected]
    ordered += [p for p in selected if p not in ordered]

    targets, runtimes, unit_map, capabilities, thresholds = [], [], {}, {}, {}
    for pid in ordered:
        profile_path = TEMPLATE_DIR / "platforms" / f"{pid}.yml"
        profile = yaml.safe_load(profile_path.read_text(encoding="utf-8")) or {}
        kind = profile.get("kind", "platform")
        unit = profile.get("unit")
        entry = {
            "id": pid,
            "kind": kind,
            "label": profile.get("label", pid),
            "profile": f"platforms/{pid}.yml",
            "unit": unit,
        }
        if profile.get("min_version"):
            entry["min_version"] = profile["min_version"]
        if kind == "runtime":
            entry["hosts"] = list(profile.get("hosts") or [])
            runtimes.append(entry)
        else:
            targets.append(entry)
        unit_map[pid] = unit
        capabilities[pid] = {
            cap["id"]: {"status": "pending", "where": "", "reason": ""}
            for cap in profile.get("capabilities") or []
        }
        thresholds[pid] = dict(profile.get("thresholds") or {})

    doc = {
        "$comment": (
            "app-quality-polish / platforms.yml — declared targets and runtimes. "
            "Every capability listed here must be marked implemented (with `where`) or "
            "not_applicable (with `reason`). Thresholds may be tightened, never loosened "
            "below the profile. A runtime (Flutter / React Native) must cover at least one "
            "declared target."
        ),
        "version": 2,
        "targets": targets,
        "runtimes": runtimes,
        "unit_map": unit_map,
        "capabilities": capabilities,
        "thresholds": thresholds,
    }
    return yaml.safe_dump(doc, allow_unicode=True, sort_keys=False, default_flow_style=False)


def format_body(cid: str, requirement: str, assertion: dict | None, measured: str,
                platform: str | None) -> str:
    if platform:
        note = f" ({platform})"
        platform_value = platform
    else:
        note = ""
        platform_value = ""
    if assertion:
        assert_comment = (
            f"# Clause asserts: {assertion['path']} {assertion.get('op', '==')} "
            f"{assertion.get('value')}\n"
        )
        leaf = (assertion.get("path") or "").split(".")[-1]
        measured = measured or f"  {leaf}: 0\n"
    else:
        assert_comment = ""
        measured = measured or "  {}\n"
    return STUB.format(
        cid=cid,
        platform_note=note,
        requirement=requirement,
        assert_comment=assert_comment,
        platform_value=platform_value,
        measured=measured,
    )


def evidence_stubs(selected: list[str]) -> list[tuple[str, str]]:
    contract = load_contract()
    stubs = []
    for clause in contract.get("clauses") or []:
        spec = clause.get("verify") or {}
        if spec.get("method") != "evidence":
            continue
        cid = clause["id"]
        requirement = clause.get("requirement", "")

        if spec.get("file_pattern"):
            for pid in selected:
                stubs.append((
                    spec["file_pattern"].replace("{platform}", pid),
                    format_body(cid, requirement, spec.get("assert"), "", pid),
                ))
            continue

        # Self-referential platform note only when the clause is platform-scoped.
        platform = clause.get("platform")
        stubs.append((
            spec.get("file") or f"evidence/{cid}.yml",
            format_body(cid, requirement, spec.get("assert"), "", platform),
        ))
    return stubs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("target", help="project directory")
    parser.add_argument(
        "--platforms",
        default=",".join(ALL_PLATFORMS),
        help=f"comma-separated targets (default: {','.join(ALL_PLATFORMS)})",
    )
    parser.add_argument("--force", action="store_true", help="overwrite existing files")
    parser.add_argument("--flat", action="store_true", help="write directly into <target>")
    args = parser.parse_args()

    selected = [p.strip() for p in args.platforms.split(",") if p.strip()]
    unknown = [p for p in selected if p not in ALL_PLATFORMS]
    if unknown:
        print(f"error: unknown platform(s): {', '.join(unknown)}", file=sys.stderr)
        print(f"known: {', '.join(ALL_PLATFORMS)}", file=sys.stderr)
        return 2
    if not selected:
        print("error: no platforms selected", file=sys.stderr)
        return 2
    if not TEMPLATE_DIR.is_dir():
        print(f"error: template dir not found: {TEMPLATE_DIR}", file=sys.stderr)
        return 2

    target = Path(args.target).expanduser()
    out = target if args.flat else target / "quality"
    out.mkdir(parents=True, exist_ok=True)

    created, skipped = [], []

    def emit(rel: str, content: str | None, src: Path | None = None) -> None:
        dst = out / rel
        if dst.exists() and not args.force:
            skipped.append(rel)
            return
        dst.parent.mkdir(parents=True, exist_ok=True)
        if src is not None:
            shutil.copyfile(src, dst)
        else:
            dst.write_text(content or "", encoding="utf-8")
        created.append(rel)

    for name in CONFIG_FILES:
        src = TEMPLATE_DIR / name
        if not src.is_file():
            print(f"error: missing template {src}", file=sys.stderr)
            return 2
        emit(name, None, src)

    for pid in selected:
        src = TEMPLATE_DIR / "platforms" / f"{pid}.yml"
        if not src.is_file():
            print(f"error: missing platform profile {src}", file=sys.stderr)
            return 2
        emit(f"platforms/{pid}.yml", None, src)

    emit("platforms.yml", build_platforms_yml(selected))

    tmpl = TEMPLATE_DIR / "evidence" / "_TEMPLATE.yml"
    if tmpl.is_file():
        emit("evidence/_TEMPLATE.yml", None, tmpl)

    for rel, body in evidence_stubs(selected):
        emit(rel, body)

    print(f"contract package -> {out}")
    kinds = [(p, profile_kind(p)) for p in selected]
    tgt = [p for p, k in kinds if k == "platform"]
    rts = [p for p, k in kinds if k == "runtime"]
    print(f"targets : {', '.join(tgt) or '(none)'}")
    print(f"runtimes: {', '.join(rts) or '(none)'}")
    if rts and not tgt:
        print("warn: runtime declared with no platform target — PLT-07 will fail until a target is added")
    for rel in created:
        print(f"  + {rel}")
    for rel in skipped:
        print(f"  = {rel} (exists, skipped)")
    print(f"\n{len(created)} created, {len(skipped)} skipped.")
    print("Next: fill entities.yml -> states -> relations -> scenarios -> flows,")
    print("      then declare every capability in platforms.yml.")
    print(f"      run: python3 verify_contract.py {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
